### ISSUE TITLE
RTL-TCP Support?

### ISSUE THREAD

**Issue by twitchyliquid64** [porjo/hamsdr#1]
Have you seen the RTL-TCP library that was made (in go) in order to make rtlamr? Its hectic, and on the plus side there are no dependencies.

Is there any plans to support such a thing?

I'm looking in the long term to implement AFSK decoding support, but my wikipedia crusade so far has produced little knowledge I can turn to code.

**Comment by porjo** [comment]
At this stage, no plans to support rtl-tcp. Hamsdr is meant to be run on the same device which runs your tuner dongle. For that reason, I don't really see a use-case for rtl-tcp.

**Comment by twitchyliquid64** [comment]
Sorry about getting back to this late.

The use case is that you no longer need to rely on binding the device directly, something beyond the reach of most users and also makes it impossible on windows. A commonly available and easy-to-install application (rtl-tcp) handles that, and this application is pure go.

I may look into forking this and doing it sometime in the future if there is no interest.

**Comment by porjo** [comment]
I have no problem with adding rtl-tcp, I just have no need for it myself at the moment. Feel free to send a pull request however.
