### ISSUE TITLE
Enable "zero sample output" for streaming to the server with squelch

### ISSUE THREAD

**Issue by kovalroma** [porjo/hamsdr#5]
There is a problem when streaming from the classical rtl_fm using ezstream with squelch.

For example this is a command
rtl_fm -f 145.575M -s 16k -l 0 | lame --scale 2 --lowpass 4.0 --highpass 0.2 -r -s 16.0 -m m - - | ezstream -c /etc/ezstream.xml

When squelch is enabled the stream stops when the squelch is triggered. When rtl_fm is squelched it does not generate any data, probably causing lame and ezstream to fail.

Mr. Wilson created a simple little change for rtl_fm which outputs values of 0 (instead of nothing) when the output is squelched. 
Here is more information 
http://lists.osmocom.org/pipermail/osmocom-sdr/2015-November/000138.html
and 
http://www.rtl-sdr.com/forum/viewtopic.php?f=7&t=141

Can I ask you to apply his code to your fork?

**Comment by porjo** [comment]
I'm a little confused - Mr Wilson released his patch in 2015, yet rtl_fm already has `-E pad` flag [since 2014](https://github.com/keenerd/rtl-sdr/commit/c813134536ef26e46cd18549f2a61bb1bca99f00) which already does this. Maybe I'm misunderstanding what the patch does?

**Comment by kovalroma** [comment]
Hm, you are right. There are few rtl-sdr repositories. 

I've checked this function here:
https://github.com/hayguen/librtlsdr
https://github.com/steve-m/librtlsdr
http://git.osmocom.org/rtl-sdr/

They don't support.  And I missed to cheсk - https://github.com/keenerd/rtl-sdr which actually support this function. 

I'am sorry for my inattention.

**Comment by porjo** [comment]
I've added a `-pad` flag now :smile:
